FROM python:2-alpine

RUN apk add --update --no-cache g++ gcc libxslt-dev
#TODO(flying pi): Move to sepparate image
RUN wget https://github.com/raccoongang/edx-platform/archive/hawthorn-rg.tar.gz ; \
    tar xvzf ./hawthorn-rg.tar.gz ;\
    mv /edx-platform-hawthorn-rg /edx

RUN pip install lxml==3.8.0 html5lib==0.999 numpy==1.6.2 requests==2.9.1 beautifulsoup==3.2.1 pyparsing==2.2.0 shapely==1.2.16
RUN pip /edx/common/lib/dogstats/
RUN pip install /edx/common/lib/capa/

RUN pip install edx/common/lib/xmodule/
